jobs:
  main:
    name: Ci
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Download Prerequisites
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Test
        run: ./check/test

name: Build

on:
  schedule:
    - cron: "5 0/3 * * *"
